### ISSUE TITLE
Reintegrate Plotly

### ISSUE THREAD

**Issue by samsoe** [samsoe/mpg_weather_warehouse#20]
For dynamic plots

**Comment by samsoe** [comment]
Plotly is currently used in the main branch.  It was removed from the 'flexdashboard' branch to speed things up.

**Comment by bglarkin** [comment]
This would be a terrific upgrade because of the added functionality, but for now it slows things down too much and breaks some of the formatting that we have. Let's consider this in the future when are skills are more terrifying.
