### ISSUE TITLE
Year Facet Grid Year Desc

### ISSUE THREAD

**Issue by samsoe** [samsoe/mpg_weather_warehouse#33]
In displaying all years present in the dataset 2013 is at on top of line plots faceted by year. Displaying by year descending would place the current year at the top of the facet stack.

**Comment by bglarkin** [comment]
@samsoe please explain what you are looking for with this issue??

**Comment by bglarkin** [comment]
The argument `as.table=FALSE` within `facet_grid()` changes the order of facets. Voilà! Facet order is reversed. See the referenced excerpt from the .Rmd file, but I changed the code for all plots in the app. https://github.com/samsoe/mpg_weather_warehouse/blob/8725fa477f2b0d42a7a34ac3cb2a726a14142b34/weather.Rmd#L107

**Comment by bglarkin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Weather app sprint: UX issues](https://trello.com/c/cJDZoCH3/249-weather-app-sprint-ux-issues)
