### ISSUE TITLE
Crux translation from R to SQL

### ISSUE THREAD

**Issue by bglarkin** [samsoe/mpg_weather_warehouse#43]
@samsoe If I remember right, this function, `atan()` is the most difficult part of translating this script to SQL. But now that I've searched for it again, maybe I'm wrong. It [looks](https://www.w3schools.com/sql/func_mysql_atan2.asp) easy enough.

https://github.com/samsoe/mpg_weather_warehouse/blob/489d1bfc74509e6b758d8509438601afa89abfe0/vector-avg-wind-direction.R#L81

**Comment by samsoe** [comment]
@bglarkin Yes, I was happy to find the atan2 function in the Standard SQL documentation here: [atan2](https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions#atan2).  We are using Standard SQL in BigQuery: [documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/migrating-from-legacy-sql)
