### ISSUE TITLE
Edit About Page

### ISSUE THREAD

**Issue by samsoe** [samsoe/mpg_weather_warehouse#47]

**Comment by bglarkin** [comment]
@samsoe I'm going to create the branch `edit-about-page` to deal with this issue; will create pull request when done.

**Comment by bglarkin** [comment]
@samsoe I edited the text and it's viewable [here](https://github.com/samsoe/mpg_weather_warehouse/blob/384724ef1e48fd1c1b69e767dc7cd2f6f567656a/weather.Rmd#L162-L173) on GitHub.

At your suggestion, I relied more heavily on the readme weather data file in google drive and cut the app's about text quite bit. It's more streamlined. I'm curious what you think of it. 

https://github.com/samsoe/mpg_weather_warehouse/blob/384724ef1e48fd1c1b69e767dc7cd2f6f567656a/weather.Rmd#L162-L173

**Comment by samsoe** [comment]
@bglarkin I think it is concise and easy to digest.
